robot_list:
  - robot_type: KUKA
    model_id: KR-180-R3200-PA
    robot_id: 0
    application: logistics
    buffer_mode: false
    simulation: false
    stream_mode: false
    motion_socket:
      network:
        - tcp_server
        - 0.0.0.0
        - 54609
      timeout:
        - 1000000
        - 60000
    status_socket:
      network:
        - tcp_server
        - 0.0.0.0
        - 54610
      timeout:
        - 30000
        - 1000
    master_socket:
      network:
        - tcp_server
        - 0.0.0.0
        - 11111
      timeout:
        - 60000
        - 60000
central_hub:
  node_name: robot_node
  notice: false
  socket:
    network:
      - tcp_client
      - 127.0.0.1
      - 10001
    timeout:
      - 60000
      - 60000
robot_model_path: ../resources/robots/models