---

#  This config file is used to test communication between xyz_robot_server and robot code.
#  user can define what they want to send to xyz_robot_server in each command in filed [robot_send].
#  And if so, robot will receive data set in field [robot_should_recv] without error.
#
#  value with any means this is a dynamic value, user should accept it whatever it is, and this value
#  may be used in other command.


valid_command_values:
  - command: 500  # heart_beat
    robot_send:
    robot_should_recv:
  - command: 502  # switch_task
    robot_send:
      task_codename: "1.t"  # string
    robot_should_recv:
  - command: 503  # switch_tool
    robot_send:
      tool_id: 0
    robot_should_recv:
  - command: 504  # call_vision_cmd
    robot_send:
      vs_id: 0
      vision_codename: "get_z"  # string
    robot_should_recv:
  - command: 507  # req_grasp_pose
    robot_send:
      vs_id: 0
    robot_should_recv:
      token: any  # it's a dynamic value
  - command: 508  # get_grasp_pose
    robot_send:
      token: any  # token value received from 507
    robot_should_recv:
      grasp_pose: [ 100.11, -200.22, 300.33, 40.44, -50.55, 60.66, 0 ]  # xyzabcd
      pose_num: 1
      pipeline_num: 0
      register_num: 0
      int_1: 1
      int_2: 2
      int_3: 3
      int_4: 4
      int_5: 5
      int_6: 6
  - command: 509  # req_object_pose
    robot_send:
      vs_id: 0
    robot_should_recv:
      token: any  # it's a dynamic value
  - command: 510  # get_object_pose
    robot_send:
      token: any  # token value received from 509
    robot_should_recv:
      object_pose: [ 101.11, -201.22, 301.33, 41.44, -51.55, 61.66, 0 ]  # xyzabcd
      pose_num: 1
      object_name: "obj1" # string
      int_1: 1
      int_2: 2
      int_3: 3
      int_4: 4
      int_5: 5
      int_6: 6
  - command: 511  # reset task
    robot_send:
    robot_should_recv:
  - command: 512  # send_current_joints
    robot_send:
      joints: [ 10.11, -20.22, 30.33, -40.44, 50.55, -60.66 ] # j1~j6
    robot_should_recv:
  - command: 513  # send_current_cart_pose
    robot_send:
      cart_pose: [ 11.11, -21.22, 31.33, -41.44, 51.55, -61.66, 0 ]  # xyzabcd
    robot_should_recv:
  - command: 514  # send_current_ext_joints
    robot_send:
      ext_joints: [ 12.11, -22.22, 32.33, -42.44, 52.55, -62.66 ] # ext j1~j6
    robot_should_recv:
  - command: 517  # req_pick_place
    robot_send:
      vs_id: 0
    robot_should_recv:
  - command: 518  # get_pick_in
    robot_send:
      vs_id: 0    # should be consistent with vs_id in req_pick_place, or it'll return failed in error_code
    robot_should_recv:
      pipeline_num: 0
      register_num: 0
      way_points: [ 11, 30.52, -20.60, -30.70, 5.59, -63.46, -15.58, 12, 35.52, -23.60, -35.70, -6.59, -68.46, -18.58, 21, 270.12, 205.34, 285.66, -165.85, -13.56, 23.12, 22, 266.12, 200.34, 290.66, -170.85, -10.56, 20.12 ]  # (way_point_type + way_points) + ...
  - command: 519  # get_pick_out
    robot_send:
      vs_id: 0    # should be consistent with vs_id in req_pick_place, or it'll return failed in error_code
    robot_should_recv:
      pipeline_num: 0
      register_num: 0
      way_points: [ 11, 30.52, -20.60, -30.70, 5.59, -63.46, -15.58, 12, 35.52, -23.60, -35.70, -6.59, -68.46, -18.58, 21, 270.12, 205.34, 285.66, -165.85, -13.56, 23.12, 22, 266.12, 200.34, 290.66, -170.85, -10.56, 20.12 ]  # (way_point_type + way_points) + ...
  - command: 520  # get_place_in
    robot_send:
      vs_id: 0    # should be consistent with vs_id in req_pick_place, or it'll return failed in error_code
    robot_should_recv:
      pipeline_num: 0
      register_num: 0
      way_points: [ 11, 30.52, -20.60, -30.70, 5.59, -63.46, -15.58, 12, 35.52, -23.60, -35.70, -6.59, -68.46, -18.58, 21, 270.12, 205.34, 285.66, -165.85, -13.56, 23.12, 22, 266.12, 200.34, 290.66, -170.85, -10.56, 20.12 ]  # (way_point_type + way_points) + ...
  - command: 521  # get_place_out
    robot_send:
      vs_id: 0    # should be consistent with vs_id in req_pick_place, or it'll return failed in error_code
    robot_should_recv:
      pipeline_num: 0
      register_num: 0
      way_points: [ 11, 30.52, -20.60, -30.70, 5.59, -63.46, -15.58, 12, 35.52, -23.60, -35.70, -6.59, -68.46, -18.58, 21, 270.12, 205.34, 285.66, -165.85, -13.56, 23.12, 22, 266.12, 200.34, 290.66, -170.85, -10.56, 20.12 ]  # (way_point_type + way_points) + ...
  - command: 523  # update_tote_pose
    robot_send:
      vs_id: 0
    robot_should_recv:
  - command: 524  # update_object_pose_in_hand
    robot_send:
    robot_should_recv:
      place_pose: [ 100.11, -200.22, 300.33, 40.44, -50.55, 60.66, 0 ]  # xyzabcd
  - command: 528  # switch item
    robot_send:
      vs_id: 0
      item_codename: "111"      # string
    robot_should_recv:
  - command: 529  # calculate grasp pose
    robot_send:
      vs_id: 0
    robot_should_recv:
      grasp_pose: [ 100.11, -200.22, 300.33, 40.44, -50.55, 60.66, 0 ]  # xyzabcd
      pose_num: 1
      pipeline_num: 0
      register_num: 0
      int_1: 1
      int_2: 2
      int_3: 3
      int_4: 4
      int_5: 5
      int_6: 6
  - command: 530  # calculate object pose
    robot_send:
      vs_id: 0
    robot_should_recv:
      object_pose: [ 101.11, -201.22, 301.33, 41.44, -51.55, 61.66, 0 ]  # xyzabcd
      pose_num: 1
      object_name: "obj1" # string
      int_1: 1
      int_2: 2
      int_3: 3
      int_4: 4
      int_5: 5
      int_6: 6
  - command: 600 # user cmd
    robot_send:
      str_list_5: [ "1", "2", "", "", "" ]
      int_list_10: [ 0,1,2,3,4,5,6,7,8,9 ]
      float_list_10: [ 1.1, 2.1, 3.1, 4.1, 5.1, -1.1, -2.1, -3.1, -4.1, -5.1 ]
      cart_pose: [ 100.11, -200.22, 300.33, 40.44, -50.55, 60.66, 0 ] #xyzabcd
      joints: [ 10.11, -20.22, 30.33, -40.44, 50.55, -60.66 ] # j1~j6
    robot_should_recv:
      str_list_5: [ "1", "2", "", "", "" ]
      int_list_10: [ 0,1,2,3,4,5,6,7,8,9 ]
      float_list_10: [ 1.1, 2.1, 3.1, 4.1, 5.1, -1.1, -2.1, -3.1, -4.1, -5.1 ]
      cart_pose: [ 100.11, -200.22, 300.33, 40.44, -50.55, 60.66, 0 ] #xyzabcd
      joints: [ 10.11, -20.22, 30.33, -40.44, 50.55, -60.66 ] # j1~j6