%YAML 1.2
---

db_num: 99
starting_byte_offset: 0
count_byte_used: 1600               # read only
communication_flags:
  range: [ 0, 2 ]                   # starting_byte_address=0, count_byte=2, that is, [0,1]
  heart_beat_flag:
    type: "bool"
    index: [ 0, 0 ]                 # starting_byte_address, bool_index
  max_ready_flag: # cmd ready
    type: "bool"
    index: [ 0, 1 ]
  max_done_flag: # cmd complete
    type: "bool"
    index: [ 0, 2 ]
  plc_request_flag:
    type: "bool"
    index: [ 0, 3 ]
recv_from_plc:
  range: [ 2, 498 ]                 # starting_byte_address=2, count_byte=498, that is, [2, 499]
  cmd:
    type: "uint"
    index: [ 2, 1 ]                 # starting_byte_address, count_int
  token:
    type: "uint"
    index: [ 4, 1 ]
  vs_id:
    type: "uint"
    index: [ 6, 1 ]
  tool_id:
    type: "uint"
    index: [ 8, 1 ]
  task_codename:
    type: "uint"
    index: [ 10, 1 ]
  item_codename:
    type: "uint"
    index: [ 12, 1 ]
  vision_codename:
    type: "uint"
    index: [ 14, 1 ]
  # [16..57] system-reserved
  cart_pose: # current_cart_pose/...
    type: "dint"
    x:
      index: [ 58, 1 ]              # starting_byte_address, count_dint
    y:
      index: [ 62, 1 ]
    z:
      index: [ 66, 1 ]
    a:
      index: [ 70, 1 ]
    b:
      index: [ 74, 1 ]
    c:
      index: [ 78, 1 ]
    d:
      index: [ 82, 1 ]
  joints: # current_joints/current_ext_joints/...
    type: "dint"
    j1:
      index: [ 86, 1 ]
    j2:
      index: [ 90, 1 ]
    j3:
      index: [ 94, 1 ]
    j4:
      index: [ 98, 1 ]
    j5:
      index: [ 102, 1 ]
    j6:
      index: [ 106, 1 ]
  usr_cmd_in:
    str_values:
      type: "chars"
      max_str_size: 50
      index: [ 110, 5 ]               # starting_byte_address, count_chars
    dint_values:
      type: "dint"
      index: [ 360, 10 ]              # starting_byte_address, count_dint
    real_value:
      type: "real"
      index: [ 400, 10 ]              # starting_byte_address, count_real
  user_defined_data: # robot_server won't update this
    type: "byte"
    index: [ 440, 60 ]
send_to_plc:
  range: [ 500, 1100 ]            # starting_byte_address=500, count_byte=1100, that is, [500, 1599]
  error:
    type: "bool"
    index: [ 500, 0 ]
  # [501] system-reserved
  error_code:
    type: "dint"
    index: [ 502, 1 ]
  token:
    type: "uint"
    index: [ 506, 1 ]
  pose_num: # grasp_pose_num/object_pose_num/...
    type: "uint"
    index: [ 508, 1 ]
  pipeline_num:
    type: "uint"
    index: [ 510, 1 ]
  register_num:
    type: "uint"
    index: [ 512, 1 ]
  object_name: # @TODO: make sure Max send number here
    type: "uint"
    index: [ 514, 1 ]
  dint_value_6: # used in calculate_grasp_pose/calculate_object_pose
    type: "dint"
    index: [ 516, 6 ]
  # [540..599] system-reserved
  cart_pose: # grasp_pose/object_pose/place_pose/...
    type: "dint"
    x:
      index: [ 600, 1 ]
    y:
      index: [ 604, 1 ]
    z:
      index: [ 608, 1 ]
    a:
      index: [ 612, 1 ]
    b:
      index: [ 616, 1 ]
    c:
      index: [ 620, 1 ]
    d:
      index: [ 624, 1 ]
  joints:
    type: "dint"
    j1:
      index: [ 628, 1 ]
    j2:
      index: [ 632, 1 ]
    j3:
      index: [ 636, 1 ]
    j4:
      index: [ 640, 1 ]
    j5:
      index: [ 644, 1 ]
    j6:
      index: [ 648, 1 ]
  usr_cmd_out:
    str_values:
      type: "chars"
      max_str_size: 50
      index: [ 652, 5 ]               # starting_byte_address, count_chars
    dint_values:
      type: "dint"
      index: [ 902, 10 ]              # starting_byte_address, count_int
    real_values:
      type: "real"
      index: [ 942, 10 ]
  trajectory: # assume one trajectory contains 20 way-points at most
    way_point_num:
      type: "uint"
      index: [ 982, 1 ]
    # [984~991] system-reserved
    way_points:
      wp_type:
        type: "byte"
        index: [ 992, 20 ]
      wp:
        type: "dint"
        index: [ 1012, 120 ]     # 120 = 6 dint * 20 way_points

        #  Explanation:
        #
        #  wp1_type: [992, 1]
        #  wp1:
        #    data1: [1012, 1]
        #    data2: [1016, 1]
        #    data3: [1020, 1]
        #    data4: [1024, 1]
        #    data5: [1028, 1]
        #    data6: [1032, 1]
        #  wp2_type: [993, 1]
        #  wp2:
        #    data1: [1036, 1]
        #    data2: [1040, 1]
        #    data3: [1044, 1]
        #    data4: [1048, 1]
        #    data5: [1052, 1]
        #    data6: [1056, 1]
        #  ...
        #  wp20_type: [1011, 1]
        #  wp20:
        #    data1: [1468, 1]
        #    data2: [1472, 1]
        #    data3: [1476, 1]
        #    data4: [1480, 1]
        #    data5: [1484, 1]
        #    data6: [1488, 1]
  user_defined_data: # [1492, 1599]
    type: "byte"
    index: [ 1492, 108 ]